### ISSUE TITLE
cannnot find module

### ISSUE THREAD

**Issue by yufeng0528** [iv-web/aegis-ivweb#7]
```
 npm version
{
  badjs_new: '1.0.0',
  npm: '6.9.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '1.1.3',
  modules: '72',
  napi: '4',
  nghttp2: '1.38.0',
  node: '12.4.0',
  openssl: '1.1.1b',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.29.1',
  v8: '7.4.288.27-node.18',
  zlib: '1.2.11'
}
```

运行npm run install 后运行npm run start报错
```
> badjs_new@1.0.0 start /data/myproduct/badjs-ivweb/badjs-ivweb
> node ./start.js

========  badjs-acceptor ===========
/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-acceptor/filter/blackListValidate.js:18
    blacklistUARegExpList.push(new RegExp(reg, 'i'));
                               ^

SyntaxError: Invalid regular expression: /*_Security_Team/: Nothing to repeat
    at new RegExp (<anonymous>)
    at /data/myproduct/badjs-ivweb/badjs-ivweb/badjs-acceptor/filter/blackListValidate.js:18:32
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-acceptor/filter/blackListValidate.js:17:21)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-acceptor/filter/blackListValidate.js:18
    blacklistUARegExpList.push(new RegExp(reg, 'i'));
                               ^

SyntaxError: Invalid regular expression: /*_Security_Team/: Nothing to repeat
    at new RegExp (<anonymous>)
    at /data/myproduct/badjs-ivweb/badjs-ivweb/badjs-acceptor/filter/blackListValidate.js:18:32
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-acceptor/filter/blackListValidate.js:17:21)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-acceptor/filter/blackListValidate.js:18
    blacklistUARegExpList.push(new RegExp(reg, 'i'));
                               ^

SyntaxError: Invalid regular expression: /*_Security_Team/: Nothing to repeat
    at new RegExp (<anonymous>)
    at /data/myproduct/badjs-ivweb/badjs-ivweb/badjs-acceptor/filter/blackListValidate.js:18:32
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-acceptor/filter/blackListValidate.js:17:21)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-acceptor/filter/blackListValidate.js:18
    blacklistUARegExpList.push(new RegExp(reg, 'i'));
                               ^

SyntaxError: Invalid regular expression: /*_Security_Team/: Nothing to repeat
    at new RegExp (<anonymous>)
    at /data/myproduct/badjs-ivweb/badjs-ivweb/badjs-acceptor/filter/blackListValidate.js:18:32
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-acceptor/filter/blackListValidate.js:17:21)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
 
 
 
 
========== badjs-mq =========
report server listen at 2001.
[2019-06-18T20:22:47.342] [INFO] default - start openapi service , port:9500
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:678:16)
    at Worker.send (internal/cluster/worker.js:43:28)
    at dispatchCluster (/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-acceptor/service/ProjectService.js:31:25)
    at ProjectService (/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-acceptor/service/ProjectService.js:61:5)
    at Timeout._onTimeout (/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-acceptor/app.js:91:44)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
Emitted 'error' event at:
    at ChildProcess.<anonymous> (internal/cluster/worker.js:27:12)
    at ChildProcess.emit (events.js:200:13)
    at internal/child_process.js:682:35
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
 
 
 
 
========= badjs-storage ==========
[2019-06-18T20:22:49.278] [INFO] default - start badjs-storage success.
report server listen at 2002.
mkdir /data/myproduct/badjs-ivweb/badjs-ivweb/badjs-storage/cache/errorMsgsuccess
mkdir /data/myproduct/badjs-ivweb/badjs-ivweb/badjs-storage/cache/totalsuccess
[2019-06-18T20:22:49.343] [ERROR] default - failed connect to mongodb
/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-storage/node_modules/mongodb/lib/mongo_client.js:421
          throw err
          ^

TypeError: Cannot read property 'db' of null
    at /data/myproduct/badjs-ivweb/badjs-ivweb/badjs-storage/storage/MongodbStorage.js:128:18
    at connectCallback (/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-storage/node_modules/mongodb/lib/mongo_client.js:527:5)
    at /data/myproduct/badjs-ivweb/badjs-ivweb/badjs-storage/node_modules/mongodb/lib/mongo_client.js:418:11
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
 
 
 
 
========== badjs-web =========
[2019-06-18 20:22:51.645] [INFO] [default] - init plugin ...
[2019-06-18 20:22:51.780] [INFO] [default] - plugin: feflow
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module './config.json'
Require stack:
- /data/myproduct/badjs-ivweb/badjs-ivweb/badjs-web/plugin/oaLogin/index.js
- /data/myproduct/badjs-ivweb/badjs-ivweb/badjs-web/workflow/PluginWorker.js
- /data/myproduct/badjs-ivweb/badjs-ivweb/badjs-web/controller/action/UserAction.js
- /data/myproduct/badjs-ivweb/badjs-ivweb/badjs-web/controller/router.js
- /data/myproduct/badjs-ivweb/badjs-ivweb/badjs-web/workflow/ExpressInitWorker.js
- /data/myproduct/badjs-ivweb/badjs-ivweb/badjs-web/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-web/plugin/oaLogin/index.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /data/myproduct/badjs-ivweb/badjs-ivweb/badjs-web/workflow/PluginWorker.js:23:21
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-web/workflow/PluginWorker.js:22:6)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-web/plugin/oaLogin/index.js',
    '/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-web/workflow/PluginWorker.js',
    '/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-web/controller/action/UserAction.js',
    '/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-web/controller/router.js',
    '/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-web/workflow/ExpressInitWorker.js',
    '/data/myproduct/badjs-ivweb/badjs-ivweb/badjs-web/app.js'
  ]
}
```

**Comment by Leo555** [comment]
config.json 里面记录了一些腾讯内部oa登录的信息，这里可以通过注释掉 badjs-web/workflow/PluginWorker.js 里面的 login （91行）跳过oa登录。
